### PR TITLE
Updating source code files for Spring Messaging course

### PR DESCRIPTION
**Pull request by dewan-ahmed**

### CODE REVIEW

**Review by ryanj — APPROVED** [review]
+1 LGTM - just make sure James and others are aware of the changes

**Comment by dewan-ahmed** [comment]
Tagging @edeandrea for his review on this (it's mostly me referring to Eric's commits to the solution branch of this course).

**Comment by edeandrea** [comment]
I will take a look tomorrow.

**Review by edeandrea — APPROVED** [review]

**Comment by edeandrea** [comment]
Looks good to me @dewan-ahmed

**Comment by dewan-ahmed** [comment]
> Looks good to me @dewan-ahmed

thanks @edeandrea

**Pull request merged**
